<template>
  <section class="py-16 bg-white">
    <div class=" mx-auto px-4 sm:px-6 lg:px-12">
      <div class="flex flex-col md:flex-row items -center">
        <!-- Image Column -->
        <div class="md:w-1/2 mb-10 md:mb-0 md:pr-10">
          <div class="overflow-hidden">
            <img 
              :src="require('/public/smartfram.svg')" 
              alt="SMART Realtors Program" 
              class="w-full h-auto object-cover"
            >
          </div>
        </div>

        <!-- Text Content Column -->
        <div class="md:w-1/2 px-4">
          <h2 class="text-xl font-semibold text-[#0033ea] uppercase tracking-wider">SMART</h2>
          <p class="text-4xl md:text-4xl font-bold text-gray-900 mb-8 leading-tight">
            Enjoy amazing rewards when you sign-up for our Realtors Program.
          </p>
          <div class="w-10/12">
              <p class="text-lg text-gray-600 mb-8">
                With SMART by Shelta, you earn direct commission in cash up to 40% on transactions.
              </p>
              <p class="text-lg text-gray-600 mb-8">
                Also, you enjoy amazing incentives as bonuses from the volume of transaction generated by you and your recruits.
              </p>
              <a 
                href="#" 
                class="inline-flex items-center text-[#0033ea] text-2xl font-medium hover:text-blue-800 transition-colors duration-200"
                @click.prevent="handleLearnMore"
              >
                Learn more
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-1" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
                </svg>
              </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'SmartProgram',
  methods: {
    handleLearnMore() {
      console.log('Learn more about SMART program clicked')
      // Add your navigation logic here
      // Example: this.$router.push('/realtors-program')
    }
  }
}
</script>

<style scoped>
/* Custom styles can be added here if needed */
.container {
  max-width: 1280px;
}

/* Responsive image sizing */
img {
  max-height: 500px;
  min-height: 300px;
  object-position: center;
}

@media (max-width: 767px) {
  img {
    min-height: 250px;
  }
}

/* Smooth hover transitions */
a {
  transition: color 0.2s ease;
}
</style>